Feature/searchfunction
DErdmann1/Pfoten-Portal pull request #18
Opened 2023-07-24 09:27 UTC by DErdmann1

Contrary to my user story, I did not add a magnifying glass icon, but instead directly display the input field. Perhaps this will be changed in a later user story that deals with styling. If no results are found, a message is displayed. Upper- or lowercase is irrelevant in the function.

2023-07-24 10:18 UTC, vaupunkt commented on components/Doglist/index.js
> +import React from "react";
you don't need to import react :)

2023-07-24 10:18 UTC, vaupunkt commented on components/Catlist/index.js
> +import React from "react";
you don't need to import react :)

2023-07-24 10:21 UTC, vaupunkt requested changes
i think you don't need three list-components and three search-functions.
in the end you can simplify it! 

in your cats, dogs or smallanimals-page you already have the filtered list for the animals. you could take this filtered list to one list-component, to render the filtered animals and retake the same component for the other animal lists. the same with the search. because you already work with filtered lists the search would work the same for all three animal-lists 😊

2023-07-24 13:57 UTC, DErdmann1 commented
I will combine the animal lists and the filtering function in another user story. However, I have deleted my React imports and adjusted the search function to update the results after each new input. :)

2023-07-25 07:26 UTC, AliaksandraNovikava approved these changes
Hey @DErdmann1 
I only checked your new changes.
Like Veliko mentioned, I would also recommend to reduce your three Searchfunction components, that are practically the same, to one. But you already said that you are planning to do so👍
I left you one comment regarding svg implementation🤓

2023-07-25 07:26 UTC, AliaksandraNovikava commented on components/Bookmarkbutton/index.js
>          </svg>
You could consider creating an external svg file and save your svg code there and then import it as component. You could reduce your code significantly🤓

2023-07-25 08:16 UTC, merged